name: Tests

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm test -- tests/regression
