name: Tests

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Google Chrome
        run: |
          # Download Chrome
          Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.86/win32/chrome-win32.zip" -OutFile "chrome-win32.zip"
          Expand-Archive -Path "chrome-win32.zip" -DestinationPath C:\chrome -Force
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm test -- tests/regression
